# Generated by Django 3.2.4 on 2021-08-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('BlogBame', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('HostName', models.CharField(max_length=50)),
                ('DateofPublished', models.DateField()),
            ],
        ),
    ]
